### ISSUE TITLE
ERROR: test.skills.wolfram_alpha (unittest.loader._FailedTest)

### ISSUE THREAD

**Issue by Sudo-Kid** [Sudo-Kid/mycroft-core#1]
Example error.

```
======================================================================
ERROR: test.skills.wolfram_alpha (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.skills.wolfram_alpha
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/the-kid/Projects/mycroft-core/test/skills/wolfram_alpha/__init__.py", line 3, in <module>
    from StringIO import StringIO
ImportError: No module named 'StringIO'
```

**Comment by Sudo-Kid** [comment]
No errors in unittests.

https://github.com/the-kid89/mycroft-core/tree/issues_1
